require 'rails_helper'

RSpec.describe FixturesService do
  describe '#fetch_fixtures' do
    let!(:gameweek) { create :gameweek }

    it 'fetches data from the API', :vcr do
      expect(FixturesService.fetch_fixtures).to eq({:count=>10,
                                                    :filters=>{:matchday=>"1"},
                                                    :competition=>
                                                    {:id=>2021,
                                                     :area=>{:id=>2072, :name=>"England"},
                                                     :name=>"Premier League",
                                                     :code=>"PL",
                                                     :plan=>"TIER_ONE",
                                                     :last_updated=>"2019-09-02T17:10:03Z"},
                                                    :matches=>
                                                    [{:id=>264341,
                                                      :season=>
                                                      {:id=>468,
                                                       :start_date=>"2019-08-09",
                                                       :end_date=>"2020-05-17",
                                                       :current_matchday=>5},
                                                      :utc_date=>"2019-08-09T19:00:00Z",
                                                      :status=>"FINISHED",
                                                      :matchday=>1,
                                                      :stage=>"REGULAR_SEASON",
                                                      :group=>"Regular Season",
                                                      :last_updated=>"2019-08-10T06:35:46Z",
                                                      :score=>
                                                      {:winner=>"HOME_TEAM",
                                                       :duration=>"REGULAR",
                                                       :full_time=>{:home_team=>4, :away_team=>1},
                                                       :half_time=>{:home_team=>4, :away_team=>0},
                                                       :extra_time=>{:home_team=>nil, :away_team=>nil},
                                                       :penalties=>{:home_team=>nil, :away_team=>nil}},
                                                      :home_team=>{:id=>64, :name=>"Liverpool FC"},
                                                      :away_team=>{:id=>68, :name=>"Norwich City FC"},
                                                      :referees=>
                                                      [{:id=>11605, :name=>"Michael Oliver", :nationality=>nil},
                                                       {:id=>11564, :name=>"Stuart Burt", :nationality=>nil},
                                                       {:id=>11488, :name=>"Simon Bennett", :nationality=>nil},
                                                       {:id=>11503, :name=>"Graham Scott", :nationality=>nil},
                                                       {:id=>11610,
                                                        :name=>"Andre Marriner",
                                                        :nationality=>nil}]},
                                                     {:id=>264342,
                                                      :season=>
                                                      {:id=>468,
                                                       :start_date=>"2019-08-09",
                                                       :end_date=>"2020-05-17",
                                                       :current_matchday=>5},
                                                      :utc_date=>"2019-08-10T11:30:00Z",
                                                      :status=>"FINISHED",
                                                      :matchday=>1,
                                                      :stage=>"REGULAR_SEASON",
                                                      :group=>"Regular Season",
                                                      :last_updated=>"2019-08-10T17:52:43Z",
                                                      :score=>
                                                      {:winner=>"AWAY_TEAM",
                                                       :duration=>"REGULAR",
                                                       :full_time=>{:home_team=>0, :away_team=>5},
                                                       :half_time=>{:home_team=>0, :away_team=>1},
                                                       :extra_time=>{:home_team=>nil, :away_team=>nil},
                                                       :penalties=>{:home_team=>nil, :away_team=>nil}},
                                                      :home_team=>{:id=>563, :name=>"West Ham United FC"},
                                                      :away_team=>{:id=>65, :name=>"Manchester City FC"},
                                                      :referees=>
                                                      [{:id=>11575, :name=>"Mike Dean", :nationality=>nil},
                                                       {:id=>11576, :name=>"Darren Cann", :nationality=>nil},
                                                       {:id=>11431,
                                                        :name=>"Daniel Robathan",
                                                        :nationality=>nil},
                                                       {:id=>9382, :name=>"Gavin Ward", :nationality=>nil},
                                                       {:id=>11556, :name=>"David Coote", :nationality=>nil}]},
                                                     {:id=>264344,
                                                      :season=>
                                                      {:id=>468,
                                                       :start_date=>"2019-08-09",
                                                       :end_date=>"2020-05-17",
                                                       :current_matchday=>5},
                                                      :utc_date=>"2019-08-10T14:00:00Z",
                                                      :status=>"FINISHED",
                                                      :matchday=>1,
                                                      :stage=>"REGULAR_SEASON",
                                                      :group=>"Regular Season",
                                                      :last_updated=>"2019-08-10T22:13:59Z",
                                                      :score=>
                                                      {:winner=>"HOME_TEAM",
                                                       :duration=>"REGULAR",
                                                       :full_time=>{:home_team=>3, :away_team=>0},
                                                       :half_time=>{:home_team=>0, :away_team=>0},
                                                       :extra_time=>{:home_team=>nil, :away_team=>nil},
                                                       :penalties=>{:home_team=>nil, :away_team=>nil}},
                                                      :home_team=>{:id=>328, :name=>"Burnley FC"},
                                                      :away_team=>{:id=>340, :name=>"Southampton FC"},
                                                      :referees=>
                                                      [{:id=>11503, :name=>"Graham Scott", :nationality=>nil},
                                                       {:id=>11424, :name=>"Neil Davies", :nationality=>nil},
                                                       {:id=>11437, :name=>"Andy Garratt", :nationality=>nil},
                                                       {:id=>9381, :name=>"Ross Joyce", :nationality=>nil},
                                                       {:id=>11309, :name=>"Peter Bankes", :nationality=>nil}]},
                                                     {:id=>264345,
                                                      :season=>
                                                      {:id=>468,
                                                       :start_date=>"2019-08-09",
                                                       :end_date=>"2020-05-17",
                                                       :current_matchday=>5},
                                                      :utc_date=>"2019-08-10T14:00:00Z",
                                                      :status=>"FINISHED",
                                                      :matchday=>1,
                                                      :stage=>"REGULAR_SEASON",
                                                      :group=>"Regular Season",
                                                      :last_updated=>"2019-08-10T22:15:25Z",
                                                      :score=>
                                                      {:winner=>"DRAW",
                                                       :duration=>"REGULAR",
                                                       :full_time=>{:home_team=>0, :away_team=>0},
                                                       :half_time=>{:home_team=>0, :away_team=>0},
                                                       :extra_time=>{:home_team=>nil, :away_team=>nil},
                                                       :penalties=>{:home_team=>nil, :away_team=>nil}},
                                                      :home_team=>{:id=>354, :name=>"Crystal Palace FC"},
                                                      :away_team=>{:id=>62, :name=>"Everton FC"},
                                                      :referees=>
                                                      [{:id=>11567, :name=>"Jonathan Moss", :nationality=>nil},
                                                       {:id=>11531, :name=>"Marc Perry", :nationality=>nil},
                                                       {:id=>11480, :name=>"Eddie Smart", :nationality=>nil},
                                                       {:id=>11536, :name=>"Craig Hicks", :nationality=>nil},
                                                       {:id=>11327, :name=>"John Brooks", :nationality=>nil}]},
                                                     {:id=>264346,
                                                      :season=>
                                                      {:id=>468,
                                                       :start_date=>"2019-08-09",
                                                       :end_date=>"2020-05-17",
                                                       :current_matchday=>5},
                                                      :utc_date=>"2019-08-10T14:00:00Z",
                                                      :status=>"FINISHED",
                                                      :matchday=>1,
                                                      :stage=>"REGULAR_SEASON",
                                                      :group=>"Regular Season",
                                                      :last_updated=>"2019-08-10T20:11:34Z",
                                                      :score=>
                                                      {:winner=>"AWAY_TEAM",
                                                       :duration=>"REGULAR",
                                                       :full_time=>{:home_team=>0, :away_team=>3},
                                                       :half_time=>{:home_team=>0, :away_team=>1},
                                                       :extra_time=>{:home_team=>nil, :away_team=>nil},
                                                       :penalties=>{:home_team=>nil, :away_team=>nil}},
                                                      :home_team=>{:id=>346, :name=>"Watford FC"},
                                                      :away_team=>{:id=>397, :name=>"Brighton & Hove Albion FC"},
                                                      :referees=>
                                                      [{:id=>11585, :name=>"Craig Pawson", :nationality=>nil},
                                                       {:id=>11495, :name=>"Ian Hussin", :nationality=>nil},
                                                       {:id=>11586, :name=>"Richard West", :nationality=>nil},
                                                       {:id=>11492, :name=>"Peter Wright", :nationality=>nil},
                                                       {:id=>11423, :name=>"Andy Madley", :nationality=>nil}]},
                                                     {:id=>264347,
                                                      :season=>
                                                      {:id=>468,
                                                       :start_date=>"2019-08-09",
                                                       :end_date=>"2020-05-17",
                                                       :current_matchday=>5},
                                                      :utc_date=>"2019-08-10T14:00:00Z",
                                                      :status=>"FINISHED",
                                                      :matchday=>1,
                                                      :stage=>"REGULAR_SEASON",
                                                      :group=>"Regular Season",
                                                      :last_updated=>"2019-08-10T20:06:07Z",
                                                      :score=>
                                                      {:winner=>"DRAW",
                                                       :duration=>"REGULAR",
                                                       :full_time=>{:home_team=>1, :away_team=>1},
                                                       :half_time=>{:home_team=>0, :away_team=>0},
                                                       :extra_time=>{:home_team=>nil, :away_team=>nil},
                                                       :penalties=>{:home_team=>nil, :away_team=>nil}},
                                                      :home_team=>{:id=>1044, :name=>"AFC Bournemouth"},
                                                      :away_team=>{:id=>356, :name=>"Sheffield United FC"},
                                                      :referees=>
                                                      [{:id=>11487, :name=>"Kevin Friend", :nationality=>nil},
                                                       {:id=>11444, :name=>"Matthew Wilkes", :nationality=>nil},
                                                       {:id=>11425,
                                                        :name=>"Nicholas Hopton",
                                                        :nationality=>nil},
                                                       {:id=>11497,
                                                        :name=>"Charles Breakspear",
                                                        :nationality=>nil},
                                                       {:id=>11479, :name=>"Lee Mason", :nationality=>nil}]},
                                                     {:id=>264348,
                                                      :season=>
                                                      {:id=>468,
                                                       :start_date=>"2019-08-09",
                                                       :end_date=>"2020-05-17",
                                                       :current_matchday=>5},
                                                      :utc_date=>"2019-08-10T16:30:00Z",
                                                      :status=>"FINISHED",
                                                      :matchday=>1,
                                                      :stage=>"REGULAR_SEASON",
                                                      :group=>"Regular Season",
                                                      :last_updated=>"2019-08-11T06:55:03Z",
                                                      :score=>
                                                      {:winner=>"HOME_TEAM",
                                                       :duration=>"REGULAR",
                                                       :full_time=>{:home_team=>3, :away_team=>1},
                                                       :half_time=>{:home_team=>0, :away_team=>1},
                                                       :extra_time=>{:home_team=>nil, :away_team=>nil},
                                                       :penalties=>{:home_team=>nil, :away_team=>nil}},
                                                      :home_team=>{:id=>73, :name=>"Tottenham Hotspur FC"},
                                                      :away_team=>{:id=>58, :name=>"Aston Villa FC"},
                                                      :referees=>
                                                      [{:id=>11443, :name=>"Chris Kavanagh", :nationality=>nil},
                                                       {:id=>11438, :name=>"Dan Cook", :nationality=>nil},
                                                       {:id=>98555, :name=>nil, :nationality=>nil},
                                                       {:id=>11396, :name=>"Tim Robinson", :nationality=>nil},
                                                       {:id=>11494,
                                                        :name=>"Stuart Attwell",
                                                        :nationality=>nil}]},
                                                     {:id=>264343,
                                                      :season=>
                                                      {:id=>468,
                                                       :start_date=>"2019-08-09",
                                                       :end_date=>"2020-05-17",
                                                       :current_matchday=>5},
                                                      :utc_date=>"2019-08-11T13:00:00Z",
                                                      :status=>"FINISHED",
                                                      :matchday=>1,
                                                      :stage=>"REGULAR_SEASON",
                                                      :group=>"Regular Season",
                                                      :last_updated=>"2019-08-12T10:45:05Z",
                                                      :score=>
                                                      {:winner=>"DRAW",
                                                       :duration=>"REGULAR",
                                                       :full_time=>{:home_team=>0, :away_team=>0},
                                                       :half_time=>{:home_team=>0, :away_team=>0},
                                                       :extra_time=>{:home_team=>nil, :away_team=>nil},
                                                       :penalties=>{:home_team=>nil, :away_team=>nil}},
                                                      :home_team=>{:id=>338, :name=>"Leicester City FC"},
                                                      :away_team=>{:id=>76, :name=>"Wolverhampton Wanderers FC"},
                                                      :referees=>
                                                      [{:id=>11610, :name=>"Andre Marriner", :nationality=>nil},
                                                       {:id=>11611, :name=>"Scott Ledger", :nationality=>nil},
                                                       {:id=>11504, :name=>"Simon Long", :nationality=>nil},
                                                       {:id=>11423, :name=>"Andy Madley", :nationality=>nil},
                                                       {:id=>11567,
                                                        :name=>"Jonathan Moss",
                                                        :nationality=>nil}]},
                                                     {:id=>264349,
                                                      :season=>
                                                      {:id=>468,
                                                       :start_date=>"2019-08-09",
                                                       :end_date=>"2020-05-17",
                                                       :current_matchday=>5},
                                                      :utc_date=>"2019-08-11T13:00:00Z",
                                                      :status=>"FINISHED",
                                                      :matchday=>1,
                                                      :stage=>"REGULAR_SEASON",
                                                      :group=>"Regular Season",
                                                      :last_updated=>"2019-08-12T10:45:05Z",
                                                      :score=>
                                                      {:winner=>"AWAY_TEAM",
                                                       :duration=>"REGULAR",
                                                       :full_time=>{:home_team=>0, :away_team=>1},
                                                       :half_time=>{:home_team=>0, :away_team=>0},
                                                       :extra_time=>{:home_team=>nil, :away_team=>nil},
                                                       :penalties=>{:home_team=>nil, :away_team=>nil}},
                                                      :home_team=>{:id=>67, :name=>"Newcastle United FC"},
                                                      :away_team=>{:id=>57, :name=>"Arsenal FC"},
                                                      :referees=>
                                                      [{:id=>11551,
                                                        :name=>"Martin Atkinson",
                                                        :nationality=>nil},
                                                       {:id=>11530, :name=>"Lee Betts", :nationality=>nil},
                                                       {:id=>11606,
                                                        :name=>"Constantine Hatzidakis",
                                                        :nationality=>nil},
                                                       {:id=>11469, :name=>"Darren England", :nationality=>nil},
                                                       {:id=>11556, :name=>"David Coote", :nationality=>nil}]},
                                                     {:id=>264350,
                                                      :season=>
                                                      {:id=>468,
                                                       :start_date=>"2019-08-09",
                                                       :end_date=>"2020-05-17",
                                                       :current_matchday=>5},
                                                      :utc_date=>"2019-08-11T15:30:00Z",
                                                      :status=>"FINISHED",
                                                      :matchday=>1,
                                                      :stage=>"REGULAR_SEASON",
                                                      :group=>"Regular Season",
                                                      :last_updated=>"2019-08-12T10:50:07Z",
                                                      :score=>
                                                      {:winner=>"HOME_TEAM",
                                                       :duration=>"REGULAR",
                                                       :full_time=>{:home_team=>4, :away_team=>0},
                                                       :half_time=>{:home_team=>1, :away_team=>0},
                                                       :extra_time=>{:home_team=>nil, :away_team=>nil},
                                                       :penalties=>{:home_team=>nil, :away_team=>nil}},
                                                      :home_team=>{:id=>66, :name=>"Manchester United FC"},
                                                      :away_team=>{:id=>61, :name=>"Chelsea FC"},
                                                      :referees=>
                                                      [{:id=>11580, :name=>"Anthony Taylor", :nationality=>nil},
                                                       {:id=>11581, :name=>"Gary Beswick", :nationality=>nil},
                                                       {:id=>11615, :name=>"Adam Nunn", :nationality=>nil},
                                                       {:id=>11479, :name=>"Lee Mason", :nationality=>nil},
                                                       {:id=>11494,
                                                        :name=>"Stuart Attwell",
                                                        :nationality=>nil}]}]})
    end
  end
end
